language: r
sudo: false
cache: packages
cran: https://cloud.r-project.org
r:
  - devel


r_packages:
  - knitr
  - rmarkdown
  - RSQLite
  - RPostgreSQL
  - ggplot2
  - reshape2
  - igraph


r_github_packages:
  - yihui/xaringan


script:
  - make
  - make deploy


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local-dir: slides
  on:
    branch: master
