language: r
sudo: required
cache: packages
cran: https://cloud.r-project.org

r_github_packages:
  - ramnathv/slidify
  - ramnathv/slidifyLibraries

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
