class: inverse, center, middle

# Travail final

<hr width="65%" size="0.3" color="orange" style="margin-top:-20px;"></hr>

---

# Objectif

Écrire un rapport sous forme d'article scientifique

---

# Consignes

Vous devez remettre les résultats de votre analyse des données de collaboration entre les étudiants de la classe.

Le rapport doit contenir :

- 3 figures, incluant l'illustration du réseau
- Un titre et un résumé
- Une courte introduction spécifiant les questions
- Une courte description de la méthode et des résultats
- Une discussion, enrichie de citations provenant de la littérature scientifique
- L'ensemble du texte doit faire 1000-1500 mots max
- Une bibliographie

---

# Consignes

Nous vous demandons de remettre les scripts permettant de générer l'ensemble du document, incluant : 

- La création de la base de données
- La correction des données originales
- L'injection des données
- Les requêtes
- La production des figures et tableaux
- Le document RMarkdown (en format Rmd) incluant des citations
- Le fichier de bibliographie

---

# Évaluation

À terme, selon les principes de science reproductible, nous devrions pouvoir exécuter l'ensemble de votre analyse sur un autre ordinateur, sans avoir à changer le code. 

Nous utiliserons la commande `tar_make` pour tout exécuter automatiquement.

Néanmoins, l'ensemble de ce matériel doit se trouver sur un dépôt git auquel vous nous donnerez accès. Dans ce dépôt se trouveront les fichiers de données originales en csv, les scripts, le document Rmd ainsi que la bibliographie.

---

# Évaluation

- Respect des consignes
  - Présence et clarté des éléments du rapport
  - Pertinence des visualisations
  - Qualité du français
- Reproductibilité
  - Utilisation appropriée du versionnage
  - Conception de la base de données
  - Requêtes
  - RMarkdown
  - Automatisation (targets)
  - structure du répertoire GitHub

Le contenu du rapport n'est pas d'une grande importance, il est prétexte à faire toutes les étapes du travail. Ne vous attardez pas à la rédaction, l'objectif est seulement de décrire rapidement votre démarche et d'utiliser `RMarkdown` pour la préparation d'un rapport. 

---
class: inverse, center, middle

# Discussion

<hr width="65%" size="0.3" color="orange" style="margin-top:-20px;"></hr>

## Le rôle de la reproductibilité sur la prévension des fraudes

---