project:
  type: book

lang: fr
number-depth: 2

book:
  title: "Méthodes en écologie computationelle"
  reader-mode: true

  page-footer:
    left: |
      **BIO500 - Méthodes en écologie computationelle** a été écrit par Victor Cameron
    right: |
      Ce livre a été construit avec <a href="https://quarto.org/">Quarto</a>.
  cover-image: bg.jpg
  favicon: logo.jpg
  site-url: https://econumuds.github.io/BIO500/
  repo-url: https://github.com/EcoNumUdS/BIO500
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - intro.qmd
    

    # Bloc 1: Planification de la collecte et organisation des données
    - part: donnees.qmd
      chapters:
        - donnees_ecologiques.qmd
        - validation.qmd

    # Bloc 1.5: Entreposer les données
    - part: entreposer.qmd
      chapters:
        - bases_de_donnees.qmd
        - sql.qmd
        - exercices_1.qmd

    # Bloc 2: Outils pour une science reproductible et transparente
    - part: reproductibilite.qmd
      chapters:
        - git.qmd
        - markdown1.qmd
        # - metadonnees.qmd
        - targets.qmd
        - targets_avance.qmd

    # Bloc 3: Utiliser les données
    # Bloc 3: Visualisation des données    
    - part: visualiser.qmd
      chapters:
        - figures.qmd
        - composantes_graphiques.qmd
        - cartes.qmd

    # Bloc 4: Communication scientifique   
    - part: communiquer.qmd
      chapters:
        - rapports_rmd.qmd
        # - intro.qmd

    # Programmation   
    - part: programmer.qmd
      chapters:
        - debugger.qmd
        # - bonnes_pratiques.qmd
        - fonctions.qmd
        # - intro.qmd

    # # Annexes
    # - part: annexes.qmd
    # chapters: 
    #   - installerR.qmd
    #   - mise_a_jour_R.qmd

    - references.qmd

    

bibliography: references.bib

format:
  html:
    theme: cosmo
    author-meta: "Victor Cameron"
  pdf:
    documentclass: scrreprt



