on:
  repository_dispatch:
    types: [trigger-build_pdf]

name: Render pdf

jobs:
  Build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: gh-pages

      - name: Sleep for 5 minutes (time to wait for html)
        uses: jakejarvis/wait-action@master
        with:
          time: '300s'

      - name: Convert html to pdf
        run: |
          for VARIABLE in `ls -d bloc*`
          do
            sudo chmod ugo+rwx $VARIABLE
            docker run --rm -t -v `pwd`:/slides astefanutti/decktape https://econumuds.github.io/BIO500/$VARIABLE/ $VARIABLE/$VARIABLE.pdf
          done

      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: slides
