on:
  repository_dispatch:
    types: [trigger-build_pdf]

name: Build pdf

jobs:
  Build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: gh-pages

      - name: Convert html to pdf
        run: |
          for VARIABLE in `ls -d bloc*`
          do
            chmod ugo+rwx $VARIABLE
            docker run --rm -t -v `pwd`:/slides astefanutti/decktape https://econumuds.github.io/BIO500/$VARIABLE/ $VARIABLE/$VARIABLE.pdf
          done

      - name: Deploy gh_pages
        run: |
          git config --global user.name 'willvieira'
          git config --global user.email 'willian.vieira@usherbrooke.ca'
          git add .
          git commit -m "deploy pdf :rocket:"
          git push origin gh-pages

