on:
  push:
    branches:
      - master

name: Build

jobs:
  Build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3'
      - uses: r-lib/actions/setup-r@v1
        with:
            r-version: '3.6.0'

      - name: Install dependencies
        run: make install

      - name: build html
        run: make
        
      - name: build pdf
        run: |
          if(!require(pagedown)) install.packages('pagedown')
          for(bloc in dir(pattern = 'bloc')) pagedown::chrome_print(input = paste0(bloc, '/index.html'), output = paste0(bloc, '/slides.pdf'))
        shell: Rscript {0}

      - name: prepare deployment
        run: make deploy
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: slides
          SINGLE_COMMIT: true
